### ISSUE TITLE
Non funziona?

### ISSUE THREAD

**Issue by fra-pel** [marcopeocchi/voe-dl#2]
Ciao,
ho provato gli "eseguibili" su diverse architetture (win,  lin-amd64 e mac-amd64) ma su tutte, qualsiasi link voe incolli il risultato è lo stesso. Non ritorna nulla, una sola volta ha scaricato un video.

**Comment by marcopeocchi** [comment]
Ciao @fra-pel. Sì ne sono a conoscenza, è un problema con le regex che controllano gli url di voe.sx.

Comunque, sto lavorando su una nuova versione che non richede youtube-dl e *speranzosamente* riesca a scaricare quasi tutte le stream video.

Vedi questa versione come una mega-alpha che ho usato per sperimentare cose con Go.
Quando avrò del tempo libero vedrò di rilasciare quella "definitiva"
